version: '1.0'
ssh:
  agent_forwarding: false
  mount_keys: true
workspaces:
- path: /x/coding/mutech-control
  mode: ro
  mount: mutech-control
containers: []
system_packages: []
packages:
  npm: []
  pip: []
  apt: []
  cargo: []
  post: []
env: {}
hostname: null
resources: {}
security:
  seccomp: unconfined
ports: []
